try {
  foo()
} catch (e) {
  throw e
}
