// Code generated by gen-eslint-core-rule-tests.ts. DO NOT EDIT.

package core_rule_tests

import (
	"testing"
)

func TestGuardForInRule(t *testing.T) {
	RunRuleTester(t, "{}", "guard-for-in", []ValidTestCase{
		{Code: `for (var x in o);`},
		{Code: `for (var x in o) {}`},
		{Code: `for (var x in o) if (x) f();`},
		{Code: `for (var x in o) { if (x) { f(); } }`},
		{Code: `for (var x in o) { if (x) continue; f(); }`},
		{Code: `for (var x in o) { if (x) { continue; } f(); }`},
	}, []InvalidTestCase{
		{
			Code: `for (var x in o) { if (x) { f(); continue; } g(); }`,
			Errors: []InvalidTestCaseError{
				{
					MessageId: "wrap",
				},
			},
		},
		{
			Code: `for (var x in o) { if (x) { continue; f(); } g(); }`,
			Errors: []InvalidTestCaseError{
				{
					MessageId: "wrap",
				},
			},
		},
		{
			Code: `for (var x in o) { if (x) { f(); } g(); }`,
			Errors: []InvalidTestCaseError{
				{
					MessageId: "wrap",
				},
			},
		},
		{
			Code: `for (var x in o) { if (x) f(); g(); }`,
			Errors: []InvalidTestCaseError{
				{
					MessageId: "wrap",
				},
			},
		},
		{
			Code: `for (var x in o) { foo() }`,
			Errors: []InvalidTestCaseError{
				{
					MessageId: "wrap",
				},
			},
		},
		{
			Code: `for (var x in o) foo();`,
			Errors: []InvalidTestCaseError{
				{
					MessageId: "wrap",
				},
			},
		},
	})
}
